Make tooltip orange when on backuplist
saproto/saproto pull request #1531
Opened 2022-04-05 21:37 UTC by ysbrandB

Change the tooltip on the included events-block from green to orange when on the backup list and announce that you are on the backuplist with the tooltip. Avoids confusion.

2022-04-09 18:26 UTC, Jessseee requested changes
I think a helper method in the activity model, like isParticipating but for the backuplist, would better than doing database queries in the blade file.

2022-04-11 10:11 UTC, ysbrandB commented
> I think a helper method in the activity model, like isParticipating but for the backuplist, would better than doing database queries in the blade file.

The logic is now moved to the controller

2022-04-12 11:53 UTC, Jessseee requested changes

2022-04-12 11:53 UTC, Jessseee commented on resources/views/event/display_includes/event_block.blade.php
> -                @endif
This will now always show the user as participating, right?

2022-04-12 11:54 UTC, Jessseee requested changes

2022-04-12 18:10 UTC, Jessseee approved these changes
LGTM

2022-04-12 18:12 UTC, merged