Add achieved date and a description to your achieved achievement to AchievementOwnership
saproto/saproto pull request #1990
Opened 2023-08-28 17:20 UTC by ysbrandB

Implements #1092 and #1659.

2023-09-06 19:16 UTC, Jessseee requested changes
LAGTM

2023-09-06 19:16 UTC, Jessseee commented on resources/views/achievement/admin_includes/awards-addone.blade.php
> +            <div class="form-group autocomplete">
Why is this a autocomplete field?

2023-09-06 19:16 UTC, Jessseee commented on resources/views/achievement/admin_includes/awards.blade.php
> +            <div class="form-group autocomplete">
again?

2023-09-08 09:22 UTC, ysbrandB commented on resources/views/achievement/admin_includes/awards-addone.blade.php
> +            <div class="form-group autocomplete">
It should not, now removed :)

2023-09-08 09:35 UTC, Jessseee commented
LGTM

2023-09-08 11:01 UTC, merged