Feature/codex tool
saproto/saproto pull request #2001
Opened 2023-09-14 15:51 UTC by ysbrandB

Incorporates the codex tool into our website.
You can click together texts and songs to integrate easily into the pdf it exports.
Adds the necessary models and migration. Also includes the new 'senate' permission.
Requires the adjusted sql dump from the old implementation to be uploaded to the database.
Also includes a command to convert the semi-markdown to actual markdown `sail artisan proto:codex-markdown-converter`.

2023-09-26 20:59 UTC, Menkveld-24 requested changes
The styling of these 3 pages also could use some improvement

<img width="1920" alt="Schermafbeelding 2023-09-26 om 22 57 04" src="https://github.com/saproto/saproto/assets/43108191/daeacab6-0326-48f8-906d-d652dd5639c4">
<img width="1920" alt="Schermafbeelding 2023-09-26 om 22 56 54" src="https://github.com/saproto/saproto/assets/43108191/3b9f3bdd-8003-4435-a7e8-3a45d5ae2719">
<img width="1920" alt="Schermafbeelding 2023-09-26 om 22 56 43" src="https://github.com/saproto/saproto/assets/43108191/254dd928-17cd-4b8b-93f6-a68a67c2aac3">

2023-09-26 20:59 UTC, Menkveld-24 commented on app/Http/Controllers/CodexController.php
> +        $song = new CodexSong();
You can leave out the $song parameter and create the song inside the saveSong function

2023-09-26 20:59 UTC, Menkveld-24 commented on app/Http/Controllers/CodexController.php
Missing return types on all functions + phpdocs and look into the implicit route binding.
Also this file is quite large. Maybe a resource controller would be nice here, e.g. codex.texts, codex.songs

2023-09-26 20:59 UTC, Menkveld-24 commented on app/Http/Controllers/CodexController.php
> +    public function exportCodex(int $id)
Please comment this function, have no clue what you're doing down there

2023-09-26 20:59 UTC, Menkveld-24 commented on app/Libraries/AlphaPDF.php
Isn't this a composer installable library?
https://github.com/royopa/alphapdf

2023-09-26 20:59 UTC, Menkveld-24 commented on app/Libraries/PDF_TOC.php
Don't know whose file this is but is this the only approach tho generate the pdf's?

2023-09-26 20:59 UTC, Menkveld-24 commented on app/Models/Codex.php
Missing casts and fillables, + if you adhere to standard laravel names you don't need to define alle the relations (is for al your models) + phpdocs

2023-09-26 20:59 UTC, Menkveld-24 commented on database/factories/CodexTextFactory.php
> +            'type_id' => $this->faker->randomNumber(),
Foreign ID that is random?

2023-09-26 20:59 UTC, Menkveld-24 commented on database/migrations/2023_09_09_195628_add_codex_tool.php
> +            $table->integer('type_id')->unsigned();
```suggestion
            $table->foreignId('codex_text_type_id')->contrained('codex_text_types');
```

Possibly add ->cascadeOnDelete()

2023-09-26 20:59 UTC, Menkveld-24 commented on database/migrations/2023_09_09_195628_add_codex_tool.php
Please define the relations (foreign keys / naming conventions) properly

2023-09-26 20:59 UTC, Menkveld-24 commented on resources/fonts/helvetica.php
What do all these file do? (comment it pls)

2023-09-26 20:59 UTC, Menkveld-24 commented on resources/views/codex/codex-edit.blade.php
> +    <form action="{{ isset($codex)&&$codex?route('codex::edit-codex', ['codex'=>$codex]):route("codex::add-codex") }}" method="POST">
Spacing
And shouldn't the linter fix this?

2023-09-26 20:59 UTC, Menkveld-24 commented on resources/views/codex/includes/song_list.blade.php
> +                                <input class="form-check-input" type="checkbox" name="shuffleids[]" {{in_array($songCategory->id, $myShuffles??[])?"checked":""}} value="{{$songCategory->id}}"> shuffl
Spacing

2023-09-26 20:59 UTC, Menkveld-24 commented on resources/views/codex/song-category-edit.blade.php
> +                                <input type="text" value="{{$category->name??""}}" class="form-control" id="name" name="name">
Spacing

2023-09-26 20:59 UTC, Menkveld-24 commented on resources/views/codex/song-category-edit.blade.php
> +    <form action="{{ isset($category)&&$category?route('codex::edit-song-category', ['id'=>$category->id]):route("codex::add-song-category") }}" method="POST">
Spacing

2023-09-26 20:59 UTC, Menkveld-24 commented on resources/views/codex/song-edit.blade.php
spacing

2023-09-26 20:59 UTC, Menkveld-24 commented on resources/views/codex/text-edit.blade.php
spacing

2023-09-26 20:59 UTC, Menkveld-24 commented on resources/views/codex/text-type-edit.blade.php
spacing

2023-09-26 20:59 UTC, Menkveld-24 commented on resources/views/website/navbar.blade.php
> +                                    <a class="nav-link" href="{{route('codex::index')}}" role="button"
spacing

2023-09-29 08:22 UTC, ysbrandB commented
> The styling of these 3 pages also could use some improvement
> 
> <img alt="Schermafbeelding 2023-09-26 om 22 57 04" width="1920" src="https://user-images.githubusercontent.com/43108191/270795227-daeacab6-0326-48f8-906d-d652dd5639c4.png"> <img alt="Schermafbeelding 2023-09-26 om 22 56 54" width="1920" src="https://user-images.githubusercontent.com/43108191/270795234-3b9f3bdd-8003-4435-a7e8-3a45d5ae2719.png"> <img alt="Schermafbeelding 2023-09-26 om 22 56 43" width="1920" src="https://user-images.githubusercontent.com/43108191/270795245-254dd928-17cd-4b8b-93f6-a68a67c2aac3.png">

Yeah this is a quick first version because the hosting of the current tool will cease to exist shortly, also the data models etc are not optimal, but compatible with the last version, When this is merged I will open a new issue with proposed improvements.

2023-09-29 08:24 UTC, ysbrandB commented on app/Http/Controllers/CodexController.php
> +        $song = CodexSong::findOrFail($id);
I tried this, could not get it to work. I was probably missing the middleware but I think we should then add this globally and refactor more than just this

2023-09-29 08:25 UTC, ysbrandB commented on app/Console/Commands/CodexMarkdownConverter.php
> +        }
This is a throway command, after the DB is imported from the last tool this will go out of our code base again.

2023-10-05 12:49 UTC, Menkveld-24 approved these changes
GEFN (Good enough for now)

See #2023 for the improvements
Merged for now as it works and the current implementation of codices will cease to exist soon

2023-10-05 12:50 UTC, merged