Feature/wallstreet custom events
saproto/saproto pull request #2062
Opened 2023-12-11 14:39 UTC by ysbrandB

Adds custom events to the wallstreet system.
For instance you can make an event that a keg fell of a truck and all weizen prizes decrease by 10%.
Shows an image in a modal with a header and a description.
![image](https://github.com/saproto/saproto/assets/72889753/5128f28a-a8e3-4b75-8313-0142a70d64a6)

2024-01-14 16:08 UTC, Menkveld-24 requested changes

2024-01-16 19:50 UTC, ysbrandB commented on app/Console/Commands/UpdateWallstreetPrices.php
> +                    'price' => $latestPrice->price + $delta >= $product->price * 1.2 ? $product->price * 1.2 : $latestPrice->price + $delta,
No, see latest commit though

2024-01-16 19:50 UTC, ysbrandB commented on app/Http/Controllers/WallstreetController.php
> +            $event->image()->dissociate();
Yes

2024-01-16 20:02 UTC, Menkveld-24 approved these changes
LGTM

2024-01-16 20:11 UTC, merged