WIP: Added Google Workspace Sync
saproto/saproto pull request #2170
Opened 2024-06-18 20:54 UTC by Jessseee

Implemented a command to synchronise users and committees to the Google Workspace.

This will create Google groups for committees and Google users for active members and add the users to the appropriate groups. It will also add aliases that point at specific users or committees. When a user is created the user's configured email will automatically be added as a forwarder in their Google Workspace Gmail. When a Google user is created the member will first have to use the password sync in their dashboard (it would be nice if users are automatically notified of this).

2024-06-18 21:03 UTC, Jessseee commented
To test this you should add `->slice(0, 1)` to the `ProtoUser::query()` in `syncProtoUsersWithGoogleUsers()` to not sync all of the seeded users to Google Workspace. Also disable the `!app()->environment('production')` check in `handle()`, or change the environment to production.

2024-08-16 18:13 UTC, ysbrandB requested changes

2024-08-16 18:13 UTC, ysbrandB commented on .env.prod
> -DISCORD_CLIENT=oauth_client_id
These should probably stay in the .env

2024-08-16 18:13 UTC, ysbrandB commented on database/seeders/DatabaseSeeder.php
> +        $adminPassword = str_random();
Should this be changed back?

2024-08-16 18:13 UTC, ysbrandB commented on database/seeders/ImportLiveDataSeeder.php
> +        $remote_url = str_replace(config('app-proto.app-url'), 'https://www.proto.utwente.nl/', $local_url);
Also here, should the / be readded here? we do not have it there in production.

2024-11-26 23:12 UTC, merged